//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Web.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LookupControlsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LookupControlsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nat.Web.Controls.Properties.LookupControlsResources", typeof(LookupControlsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить фильтр.
        /// </summary>
        internal static string SApplyFilter {
            get {
                return ResourceManager.GetString("SApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string SCancel {
            get {
                return ResourceManager.GetString("SCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить краткий вид фильтра.
        /// </summary>
        internal static string SChangeToBriefView {
            get {
                return ResourceManager.GetString("SChangeToBriefView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить развёрнутый вид фильтра.
        /// </summary>
        internal static string SChangeToFullView {
            get {
                return ResourceManager.GetString("SChangeToFullView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        internal static string SData {
            get {
                return ResourceManager.GetString("SData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string SFalse {
            get {
                return ResourceManager.GetString("SFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установлен фильтр.
        /// </summary>
        internal static string SFilterApplied {
            get {
                return ResourceManager.GetString("SFilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критерии отбора.
        /// </summary>
        internal static string SFilterCriteria {
            get {
                return ResourceManager.GetString("SFilterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примените фильтр.
        /// </summary>
        internal static string SFilterNotApplied {
            get {
                return ResourceManager.GetString("SFilterNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть фильтр.
        /// </summary>
        internal static string SHideFilter {
            get {
                return ResourceManager.GetString("SHideFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных, которые удовлетворяют данному фильтру.
        /// </summary>
        internal static string SNoDataByFilterCriteria {
            get {
                return ResourceManager.GetString("SNoDataByFilterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить текущий фильтр.
        /// </summary>
        internal static string SSaveFiltersState {
            get {
                return ResourceManager.GetString("SSaveFiltersState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string SSelect {
            get {
                return ResourceManager.GetString("SSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор из справочника.
        /// </summary>
        internal static string SSelectFromDBDirectory {
            get {
                return ResourceManager.GetString("SSelectFromDBDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать фильтр.
        /// </summary>
        internal static string SShowFilter {
            get {
                return ResourceManager.GetString("SShowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string STrue {
            get {
                return ResourceManager.GetString("STrue", resourceCulture);
            }
        }
    }
}
