//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Web.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nat.Web.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить запись, используется в системе.
        /// </summary>
        public static string ECanNotDeleteUseInSystem {
            get {
                return ResourceManager.GetString("ECanNotDeleteUseInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя редактировать запись.
        /// </summary>
        public static string ECanNotEditRecord {
            get {
                return ResourceManager.GetString("ECanNotEditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на добавление.
        /// </summary>
        public static string EDoesNotHavePermitForAdd {
            get {
                return ResourceManager.GetString("EDoesNotHavePermitForAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на редактирование.
        /// </summary>
        public static string EDoesNotHavePermitForEdit {
            get {
                return ResourceManager.GetString("EDoesNotHavePermitForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать больше {0} записей запрещено. Используйте фильтр что бы получить меньший список..
        /// </summary>
        public static string EExportMaxCountRecords {
            get {
                return ResourceManager.GetString("EExportMaxCountRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле &apos;{0}&apos; превышено максимальное количество символов: {0}.
        /// </summary>
        public static string EFieldMaxLength {
            get {
                return ResourceManager.GetString("EFieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;{0}&apos; должно быть меньше поля &apos;{1}&apos;..
        /// </summary>
        public static string EFieldMustBeLessOfField {
            get {
                return ResourceManager.GetString("EFieldMustBeLessOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;{0}&apos; должно быть меньше или равно полю &apos;{1}&apos;..
        /// </summary>
        public static string EFieldMustBeLessOrEqualsOfField {
            get {
                return ResourceManager.GetString("EFieldMustBeLessOrEqualsOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;{0}&apos; должно быть больше поля &apos;{1}&apos;..
        /// </summary>
        public static string EFieldMustBeMoreOfField {
            get {
                return ResourceManager.GetString("EFieldMustBeMoreOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;{0}&apos; должно быть больше или равно полю &apos;{1}&apos;..
        /// </summary>
        public static string EFieldMustBeMoreOrEqualsOfField {
            get {
                return ResourceManager.GetString("EFieldMustBeMoreOrEqualsOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное количество символов: {0}.
        /// </summary>
        public static string EMaxLength {
            get {
                return ResourceManager.GetString("EMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть меньше поля &apos;{0}&apos;..
        /// </summary>
        public static string EMustBeLessOfField {
            get {
                return ResourceManager.GetString("EMustBeLessOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть меньше или равно полю &apos;{0}&apos;..
        /// </summary>
        public static string EMustBeLessOrEqualsOfField {
            get {
                return ResourceManager.GetString("EMustBeLessOrEqualsOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть больше поля &apos;{0}&apos;..
        /// </summary>
        public static string EMustBeMoreOfField {
            get {
                return ResourceManager.GetString("EMustBeMoreOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть больше или равно полю &apos;{0}&apos;..
        /// </summary>
        public static string EMustBeMoreOrEqualsOfField {
            get {
                return ResourceManager.GetString("EMustBeMoreOrEqualsOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на удаление записи.
        /// </summary>
        public static string ENoPermitToDeleteRecord {
            get {
                return ResourceManager.GetString("ENoPermitToDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произведено автоматическое заполнение поля &apos;{0}&apos; значением, которое не может быть сохранено..
        /// </summary>
        public static string ENotCorrectDefaultValue {
            get {
                return ResourceManager.GetString("ENotCorrectDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произведено автоматическое заполнение поля &apos;{0}&apos; значением &apos;{1}&apos;, которое не может быть сохранено..
        /// </summary>
        public static string ENotCorrectDefaultValueWithText {
            get {
                return ResourceManager.GetString("ENotCorrectDefaultValueWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно выбрано значение в поле &apos;{0}&apos;, которое не может быть сохранено, пожалуйста выберите повторно..
        /// </summary>
        public static string ENotCorrectValue {
            get {
                return ResourceManager.GetString("ENotCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно выбрано значение &apos;{1}&apos; в поле &apos;{0}&apos;, которое не может быть сохранено, пожалуйста выберите повторно..
        /// </summary>
        public static string ENotCorrectValueWithText {
            get {
                return ResourceManager.GetString("ENotCorrectValueWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует запись или наименование записи.
        /// </summary>
        public static string ENotExistsRowOrName {
            get {
                return ResourceManager.GetString("ENotExistsRowOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись была кем-то изменена.
        /// </summary>
        public static string ERecordModifiedByOther {
            get {
                return ResourceManager.GetString("ERecordModifiedByOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная запись была удалена другим пользователем..
        /// </summary>
        public static string ERecordWasDeletedByOtherUser {
            get {
                return ResourceManager.GetString("ERecordWasDeletedByOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Были внесены изменения другим пользователем..
        /// </summary>
        public static string ERecordWasSavedByOtherUser {
            get {
                return ResourceManager.GetString("ERecordWasSavedByOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись удалена или недостаточно прав.
        /// </summary>
        public static string ERowIsDeletedOrNotHavePermissions {
            get {
                return ResourceManager.GetString("ERowIsDeletedOrNotHavePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на экспорт журнала &quot;{0}&quot;.
        /// </summary>
        public static string EUserDoesNotHaveExportPermitions {
            get {
                return ResourceManager.GetString("EUserDoesNotHaveExportPermitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на просмотр журнала &quot;{0}&quot;.
        /// </summary>
        public static string EUserDoesNotHaveViewPermitions {
            get {
                return ResourceManager.GetString("EUserDoesNotHaveViewPermitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть группу.
        /// </summary>
        public static string PressToCloseGroup {
            get {
                return ResourceManager.GetString("PressToCloseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По нажатию разворачивается/сворачивается группа.
        /// </summary>
        public static string PressToOpenCloseGroup {
            get {
                return ResourceManager.GetString("PressToOpenCloseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть группу.
        /// </summary>
        public static string PressToOpenGroup {
            get {
                return ResourceManager.GetString("PressToOpenGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен.
        /// </summary>
        public static string SAccessDanied {
            get {
                return ResourceManager.GetString("SAccessDanied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string SAdd {
            get {
                return ResourceManager.GetString("SAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указана группировка для заголовка.
        /// </summary>
        public static string SAddedGroupColumnInHeader {
            get {
                return ResourceManager.GetString("SAddedGroupColumnInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объединяются ячейки группы строк.
        /// </summary>
        public static string SAddedGroupColumnLeft {
            get {
                return ResourceManager.GetString("SAddedGroupColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объединяются ячейки группы строк с итогами.
        /// </summary>
        public static string SAddedGroupColumnLeftTotal {
            get {
                return ResourceManager.GetString("SAddedGroupColumnLeftTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указана группировка.
        /// </summary>
        public static string SAddedGroupColumnTop {
            get {
                return ResourceManager.GetString("SAddedGroupColumnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указана группировка с итогами.
        /// </summary>
        public static string SAddedGroupColumnTopTotal {
            get {
                return ResourceManager.GetString("SAddedGroupColumnTopTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан итог.
        /// </summary>
        public static string SAddedGroupColumnTotal {
            get {
                return ResourceManager.GetString("SAddedGroupColumnTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фильтр.
        /// </summary>
        public static string SAddFilter {
            get {
                return ResourceManager.GetString("SAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить группировку.
        /// </summary>
        public static string SAddGroupColumn {
            get {
                return ResourceManager.GetString("SAddGroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить группировку в заголовок.
        /// </summary>
        public static string SAddGroupColumnInHeader {
            get {
                return ResourceManager.GetString("SAddGroupColumnInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировать объединяя ячейки строк.
        /// </summary>
        public static string SAddGroupColumnLeft {
            get {
                return ResourceManager.GetString("SAddGroupColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировать объединяя ячейки строк с итогом.
        /// </summary>
        public static string SAddGroupColumnLeftTotal {
            get {
                return ResourceManager.GetString("SAddGroupColumnLeftTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить группировку.
        /// </summary>
        public static string SAddGroupColumnTop {
            get {
                return ResourceManager.GetString("SAddGroupColumnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить группировку с итогом.
        /// </summary>
        public static string SAddGroupColumnTopTotal {
            get {
                return ResourceManager.GetString("SAddGroupColumnTopTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить итог.
        /// </summary>
        public static string SAddGroupColumnTotal {
            get {
                return ResourceManager.GetString("SAddGroupColumnTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление.
        /// </summary>
        public static string SAddingText {
            get {
                return ResourceManager.GetString("SAddingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить запись.
        /// </summary>
        public static string SAddRecord {
            get {
                return ResourceManager.GetString("SAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее.
        /// </summary>
        public static string SAggregateAvg {
            get {
                return ResourceManager.GetString("SAggregateAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string SAggregateCount {
            get {
                return ResourceManager.GetString("SAggregateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст группы.
        /// </summary>
        public static string SAggregateGroupText {
            get {
                return ResourceManager.GetString("SAggregateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводится текст группы.
        /// </summary>
        public static string SAggregateGroupTextToolTip {
            get {
                return ResourceManager.GetString("SAggregateGroupTextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого за &quot;группа&quot;.
        /// </summary>
        public static string SAggregateGroupTextWithTotalPhrase {
            get {
                return ResourceManager.GetString("SAggregateGroupTextWithTotalPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводится фраза &quot;Итого за &quot; и текст группы .
        /// </summary>
        public static string SAggregateGroupTextWithTotalPhraseToolTip {
            get {
                return ResourceManager.GetString("SAggregateGroupTextWithTotalPhraseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное.
        /// </summary>
        public static string SAggregateMax {
            get {
                return ResourceManager.GetString("SAggregateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальное.
        /// </summary>
        public static string SAggregateMin {
            get {
                return ResourceManager.GetString("SAggregateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без итога.
        /// </summary>
        public static string SAggregateNone {
            get {
                return ResourceManager.GetString("SAggregateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Числа.
        /// </summary>
        public static string SAggregateNumericGroup {
            get {
                return ResourceManager.GetString("SAggregateNumericGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        public static string SAggregateSum {
            get {
                return ResourceManager.GetString("SAggregateSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст группы итога.
        /// </summary>
        public static string SAggregateTextGroup {
            get {
                return ResourceManager.GetString("SAggregateTextGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать верхний уровень заголовка.
        /// </summary>
        public static string SAllHierarchy {
            get {
                return ResourceManager.GetString("SAllHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить фильтр.
        /// </summary>
        public static string SApplyFilter {
            get {
                return ResourceManager.GetString("SApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Между.
        /// </summary>
        public static string SBetween {
            get {
                return ResourceManager.GetString("SBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена добавления.
        /// </summary>
        public static string SCancelAdd {
            get {
                return ResourceManager.GetString("SCancelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прекратить действие заливки.
        /// </summary>
        public static string SCancelColorFill {
            get {
                return ResourceManager.GetString("SCancelColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прекратить действие указание цвета.
        /// </summary>
        public static string SCancelFontColorFill {
            get {
                return ResourceManager.GetString("SCancelFontColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string SCancelText {
            get {
                return ResourceManager.GetString("SCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string SCCCApplyConcatenateColumns {
            get {
                return ResourceManager.GetString("SCCCApplyConcatenateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string SCCCCancelConcatenateColumns {
            get {
                return ResourceManager.GetString("SCCCCancelConcatenateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string SCCCDeleteConcatenateColumns {
            get {
                return ResourceManager.GetString("SCCCDeleteConcatenateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список объединенных колонок.
        /// </summary>
        public static string SCCConcatenatedColumnsTitle {
            get {
                return ResourceManager.GetString("SCCConcatenatedColumnsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить для объединения.
        /// </summary>
        public static string SCCFromLeftToRight {
            get {
                return ResourceManager.GetString("SCCFromLeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить из объединения.
        /// </summary>
        public static string SCCFromRightToLeft {
            get {
                return ResourceManager.GetString("SCCFromRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные для объединения колонки.
        /// </summary>
        public static string SCCLeftColumnListTitle {
            get {
                return ResourceManager.GetString("SCCLeftColumnListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объединяемые колонки.
        /// </summary>
        public static string SCCRightColumnListTitle {
            get {
                return ResourceManager.GetString("SCCRightColumnListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Залить ячейки цветом.
        /// </summary>
        public static string SCellColorFill {
            get {
                return ResourceManager.GetString("SCellColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указать цвет текста ячейки.
        /// </summary>
        public static string SCellFontColorFill {
            get {
                return ResourceManager.GetString("SCellFontColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения данных.
        /// </summary>
        public static string SChangedData {
            get {
                return ResourceManager.GetString("SChangedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить высоту поля.
        /// </summary>
        public static string SChangeHieght {
            get {
                return ResourceManager.GetString("SChangeHieght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить высоту поля.
        /// </summary>
        public static string SChangeHieghtLess {
            get {
                return ResourceManager.GetString("SChangeHieghtLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить высоту поля.
        /// </summary>
        public static string SChangeHieghtMore {
            get {
                return ResourceManager.GetString("SChangeHieghtMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не содержит данные.
        /// </summary>
        public static string SChildDataContainsFalseText {
            get {
                return ResourceManager.GetString("SChildDataContainsFalseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит данные.
        /// </summary>
        public static string SChildDataContainsTrueText {
            get {
                return ResourceManager.GetString("SChildDataContainsTrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить фильтр.
        /// </summary>
        public static string SClearFilter {
            get {
                return ResourceManager.GetString("SClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string SClearText {
            get {
                return ResourceManager.GetString("SClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string SClose {
            get {
                return ResourceManager.GetString("SClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на см..
        /// </summary>
        public static string Scm {
            get {
                return ResourceManager.GetString("Scm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Палитра.
        /// </summary>
        public static string SColorPalette {
            get {
                return ResourceManager.GetString("SColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Залить колонки цветом.
        /// </summary>
        public static string SColumnColorFill {
            get {
                return ResourceManager.GetString("SColumnColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указать цвет текста колонки.
        /// </summary>
        public static string SColumnFontColorFill {
            get {
                return ResourceManager.GetString("SColumnFontColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объединить колонки.
        /// </summary>
        public static string SConcatenateColumns {
            get {
                return ResourceManager.GetString("SConcatenateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить?.
        /// </summary>
        public static string SConfirmDeleteText {
            get {
                return ResourceManager.GetString("SConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string SConfirmTitleText {
            get {
                return ResourceManager.GetString("SConfirmTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит.
        /// </summary>
        public static string SContains {
            get {
                return ResourceManager.GetString("SContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любой из.
        /// </summary>
        public static string SContainsAnyWord {
            get {
                return ResourceManager.GetString("SContainsAnyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит слова.
        /// </summary>
        public static string SContainsWords {
            get {
                return ResourceManager.GetString("SContainsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на изменений {0}.
        /// </summary>
        public static string SCountChanges {
            get {
                return ResourceManager.GetString("SCountChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строк: {0}.
        /// </summary>
        public static string SCountData {
            get {
                return ResourceManager.GetString("SCountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страницы: ({0}).
        /// </summary>
        public static string SCountPages {
            get {
                return ResourceManager.GetString("SCountPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий цвет.
        /// </summary>
        public static string SCurrentColor {
            get {
                return ResourceManager.GetString("SCurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтры данных.
        /// </summary>
        public static string SDataFilters {
            get {
                return ResourceManager.GetString("SDataFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период.
        /// </summary>
        public static string SDateBetween {
            get {
                return ResourceManager.GetString("SDateBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раньше.
        /// </summary>
        public static string SDateLess {
            get {
                return ResourceManager.GetString("SDateLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позже.
        /// </summary>
        public static string SDateMore {
            get {
                return ResourceManager.GetString("SDateMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошло от N дней.
        /// </summary>
        public static string SDaysAgoAndMore {
            get {
                return ResourceManager.GetString("SDaysAgoAndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось от N дней.
        /// </summary>
        public static string SDaysLeftAndMore {
            get {
                return ResourceManager.GetString("SDaysLeftAndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string SDeleteText {
            get {
                return ResourceManager.GetString("SDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опустить группу ниже.
        /// </summary>
        public static string SDownGroup {
            get {
                return ResourceManager.GetString("SDownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string SDownLoad {
            get {
                return ResourceManager.GetString("SDownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование.
        /// </summary>
        public static string SEdit {
            get {
                return ResourceManager.GetString("SEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр/Редактирование.
        /// </summary>
        public static string SEditLook {
            get {
                return ResourceManager.GetString("SEditLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string SEditText {
            get {
                return ResourceManager.GetString("SEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных.
        /// </summary>
        public static string SEmptyDataText {
            get {
                return ResourceManager.GetString("SEmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо обновить страницу..
        /// </summary>
        public static string SEndCrossDataEdit {
            get {
                return ResourceManager.GetString("SEndCrossDataEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оканчивается на.
        /// </summary>
        public static string SEndsWith {
            get {
                return ResourceManager.GetString("SEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Равно.
        /// </summary>
        public static string SEquals {
            get {
                return ResourceManager.GetString("SEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string SError {
            get {
                return ResourceManager.GetString("SError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационное сообщение.
        /// </summary>
        public static string SErrorHeaderText {
            get {
                return ResourceManager.GetString("SErrorHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string SErrorMessageTitle {
            get {
                return ResourceManager.GetString("SErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при выполнении операции, перезагрузить страницу и попробуйте еще раз..
        /// </summary>
        public static string SExceptionOccurredTryAgainOrReload {
            get {
                return ResourceManager.GetString("SExceptionOccurredTryAgainOrReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        public static string SExport {
            get {
                return ResourceManager.GetString("SExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранное значение в поле &apos;{0}&apos; имеет ошибку:.
        /// </summary>
        public static string SFieldHasError {
            get {
                return ResourceManager.GetString("SFieldHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранное значение &apos;{1}&apos; в поле &apos;{0}&apos; имеет ошибку:.
        /// </summary>
        public static string SFieldHasErrorWithText {
            get {
                return ResourceManager.GetString("SFieldHasErrorWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название файла.
        /// </summary>
        public static string SFileName {
            get {
                return ResourceManager.GetString("SFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string SFilter {
            get {
                return ResourceManager.GetString("SFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На дату.
        /// </summary>
        public static string SFilterByPeriod {
            get {
                return ResourceManager.GetString("SFilterByPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтровать заголовок.
        /// </summary>
        public static string SFilterHeader {
            get {
                return ResourceManager.GetString("SFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо изменить фильтр, т.к. за отведенное время не удалось выбрать необходимые данные. Не рекомендуется использовать критерии &quot;Содержит&quot;, &quot;Содержит слова&quot;, &quot;Оканчивается на&quot;. Рекомендуется использовать критерий &quot;Равно&quot; или &quot;Не равно&quot;..
        /// </summary>
        public static string SFilterInSqlTimeOutException {
            get {
                return ResourceManager.GetString("SFilterInSqlTimeOutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировка не указана.
        /// </summary>
        public static string SGroupColumnNotSet {
            get {
                return ResourceManager.GetString("SGroupColumnNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировка в журнале.
        /// </summary>
        public static string SGroupOfJournal {
            get {
                return ResourceManager.GetString("SGroupOfJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтры заголовка.
        /// </summary>
        public static string SHeaderFilters {
            get {
                return ResourceManager.GetString("SHeaderFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        public static string SHeight {
            get {
                return ResourceManager.GetString("SHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string SHelp {
            get {
                return ResourceManager.GetString("SHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть историю.
        /// </summary>
        public static string SHideHistory {
            get {
                return ResourceManager.GetString("SHideHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string SInfoMessageTitle {
            get {
                return ResourceManager.GetString("SInfoMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строки, имеющие ошибки, сохранены не будут.
        /// </summary>
        public static string SInfoNotSaveInvalidated {
            get {
                return ResourceManager.GetString("SInfoNotSaveInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string SInformationText {
            get {
                return ResourceManager.GetString("SInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите необходимый формат.
        /// </summary>
        public static string SInputFormat {
            get {
                return ResourceManager.GetString("SInputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите необходимый формат.
        /// </summary>
        public static string SInputFormatList {
            get {
                return ResourceManager.GetString("SInputFormatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить.
        /// </summary>
        public static string SInsertText {
            get {
                return ResourceManager.GetString("SInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введены некорректные данные..
        /// </summary>
        public static string SInvalidBindingInput {
            get {
                return ResourceManager.GetString("SInvalidBindingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно введена дата в поле фильтра &quot;{0}&quot;..
        /// </summary>
        public static string SInvalidDateFormatInFilter {
            get {
                return ResourceManager.GetString("SInvalidDateFormatInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задан неверный формат поля: {0}.
        /// </summary>
        public static string SInvalidFieldFormat {
            get {
                return ResourceManager.GetString("SInvalidFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенное значение не соответствует формату в поле фильтра &quot;{0}&quot;..
        /// </summary>
        public static string SInvalidFormatInFilter {
            get {
                return ResourceManager.GetString("SInvalidFormatInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно введено число в поле фильтра &quot;{0}&quot;..
        /// </summary>
        public static string SInvalidNumericFormatInFilter {
            get {
                return ResourceManager.GetString("SInvalidNumericFormatInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполнено.
        /// </summary>
        public static string SIsFilled {
            get {
                return ResourceManager.GetString("SIsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не заполнено.
        /// </summary>
        public static string SIsNotFilled {
            get {
                return ResourceManager.GetString("SIsNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал.
        /// </summary>
        public static string SJournal {
            get {
                return ResourceManager.GetString("SJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина меньше.
        /// </summary>
        public static string SLengthLess {
            get {
                return ResourceManager.GetString("SLengthLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина больше.
        /// </summary>
        public static string SLengthMore {
            get {
                return ResourceManager.GetString("SLengthMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меньше.
        /// </summary>
        public static string SLess {
            get {
                return ResourceManager.GetString("SLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить фильтры (если сохранены).
        /// </summary>
        public static string SLoadFilters {
            get {
                return ResourceManager.GetString("SLoadFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string SLoading {
            get {
                return ResourceManager.GetString("SLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить сохраненные настройки.
        /// </summary>
        public static string SLoadViewSettings {
            get {
                return ResourceManager.GetString("SLoadViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохраненные настройки.
        /// </summary>
        public static string SLoadViewSettings_SavedSettings {
            get {
                return ResourceManager.GetString("SLoadViewSettings_SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применение сохраненных настроек.
        /// </summary>
        public static string SLoadViewSettingsHeader {
            get {
                return ResourceManager.GetString("SLoadViewSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно сделать запись в журнал сообщений. Нескольким учётным карточкам соответствует одни SID - &apos;{0}&apos;..
        /// </summary>
        public static string SLogErrorMultipleUsers {
            get {
                return ResourceManager.GetString("SLogErrorMultipleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр.
        /// </summary>
        public static string SLook {
            get {
                return ResourceManager.GetString("SLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена допустимая длина {0} символов.
        /// </summary>
        public static string SMaxLength {
            get {
                return ResourceManager.GetString("SMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина поля &apos;{0}&apos; {1} символов.
        /// </summary>
        public static string SMaxLengthOfField {
            get {
                return ResourceManager.GetString("SMaxLengthOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная вложенность в заголовке.
        /// </summary>
        public static string SMaxRecursionInHeader {
            get {
                return ResourceManager.GetString("SMaxRecursionInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Больше.
        /// </summary>
        public static string SMore {
            get {
                return ResourceManager.GetString("SMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опустить запись ниже.
        /// </summary>
        public static string SMoveDownRecord {
            get {
                return ResourceManager.GetString("SMoveDownRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опустить запись ниже на (количество строк):.
        /// </summary>
        public static string SMoveDownRecordOn {
            get {
                return ResourceManager.GetString("SMoveDownRecordOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить вес.
        /// </summary>
        public static string SMoveDownWeight {
            get {
                return ResourceManager.GetString("SMoveDownWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поднять запись выше.
        /// </summary>
        public static string SMoveUpRecord {
            get {
                return ResourceManager.GetString("SMoveUpRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поднять запись выше на (количество строк):.
        /// </summary>
        public static string SMoveUpRecordOn {
            get {
                return ResourceManager.GetString("SMoveUpRecordOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить вес.
        /// </summary>
        public static string SMoveUpWeight {
            get {
                return ResourceManager.GetString("SMoveUpWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор записей.
        /// </summary>
        public static string SMultipleSelect {
            get {
                return ResourceManager.GetString("SMultipleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрано записей: {0}.
        /// </summary>
        public static string SMultipleSelectedMessage {
            get {
                return ResourceManager.GetString("SMultipleSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование (КАЗ).
        /// </summary>
        public static string SNameKz {
            get {
                return ResourceManager.GetString("SNameKz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование (РУС).
        /// </summary>
        public static string SNameRu {
            get {
                return ResourceManager.GetString("SNameRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню навигации.
        /// </summary>
        public static string SNavigationMenu {
            get {
                return ResourceManager.GetString("SNavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string SNewText {
            get {
                return ResourceManager.GetString("SNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string SNo {
            get {
                return ResourceManager.GetString("SNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ни одна запись не выбрана.
        /// </summary>
        public static string SNoOneSelectedRow {
            get {
                return ResourceManager.GetString("SNoOneSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ни одна запись не выбрана. Проставьте галочки..
        /// </summary>
        public static string SNoOneSelectedRowCheckRecords {
            get {
                return ResourceManager.GetString("SNoOneSelectedRowCheckRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не содержит.
        /// </summary>
        public static string SNotContains {
            get {
                return ResourceManager.GetString("SNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не содержит слова.
        /// </summary>
        public static string SNotContainsWords {
            get {
                return ResourceManager.GetString("SNotContainsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно введено число.
        /// </summary>
        public static string SNotCorrectNumber {
            get {
                return ResourceManager.GetString("SNotCorrectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно введено число..
        /// </summary>
        public static string SNotCorrectNumberForWeight {
            get {
                return ResourceManager.GetString("SNotCorrectNumberForWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно введено число поле &apos;{0}&apos;.
        /// </summary>
        public static string SNotCorrectNumberOfField {
            get {
                return ResourceManager.GetString("SNotCorrectNumberOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не равно.
        /// </summary>
        public static string SNotEquals {
            get {
                return ResourceManager.GetString("SNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Сохраненное значение недоступно&gt;.
        /// </summary>
        public static string SNotExistRow {
            get {
                return ResourceManager.GetString("SNotExistRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись не выбрана или отсутствует..
        /// </summary>
        public static string SNotSelectRecordOrNotExists {
            get {
                return ResourceManager.GetString("SNotSelectRecordOrNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано.
        /// </summary>
        public static string SNotSpecified {
            get {
                return ResourceManager.GetString("SNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На казахском.
        /// </summary>
        public static string SOnKz {
            get {
                return ResourceManager.GetString("SOnKz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На русском.
        /// </summary>
        public static string SOnRu {
            get {
                return ResourceManager.GetString("SOnRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать.
        /// </summary>
        public static string SOrderByColumn {
            get {
                return ResourceManager.GetString("SOrderByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать в обратном порядке.
        /// </summary>
        public static string SOrderByColumnDesc {
            get {
                return ResourceManager.GetString("SOrderByColumnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить сортировку.
        /// </summary>
        public static string SOrderByColumnRemove {
            get {
                return ResourceManager.GetString("SOrderByColumnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string SPleaseWait {
            get {
                return ResourceManager.GetString("SPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файл.
        /// </summary>
        public static string SPostFileFromDialog {
            get {
                return ResourceManager.GetString("SPostFileFromDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файл картинку из буфера обмена (картинка из буфера обмена загружается JPEG файлом).
        /// </summary>
        public static string SPostFileImageFromClipboard {
            get {
                return ResourceManager.GetString("SPostFileImageFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить текстовый файл из буфера обмена (текст из буфера обмена загружается файлом).
        /// </summary>
        public static string SPostFileTextFromClipboard {
            get {
                return ResourceManager.GetString("SPostFileTextFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строки, имеющие ошибки, сохранены не будут. Продолжить?.
        /// </summary>
        public static string SQuestionNotSaveInvalidated {
            get {
                return ResourceManager.GetString("SQuestionNotSaveInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрый поиск.
        /// </summary>
        public static string SQuickSearch {
            get {
                return ResourceManager.GetString("SQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит только целые числа от &quot;{0}&quot; до &quot;{1}&quot;.
        /// </summary>
        public static string SRangeValidatorErrorMessage {
            get {
                return ResourceManager.GetString("SRangeValidatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;{2}&quot; может содержать только целые числа от &quot;{0}&quot; до &quot;{1}&quot;.
        /// </summary>
        public static string SRangeValidatorErrorMessageInSummary {
            get {
                return ResourceManager.GetString("SRangeValidatorErrorMessageInSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string SRefresh {
            get {
                return ResourceManager.GetString("SRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убрать все группировки.
        /// </summary>
        public static string SRemoveAllGroups {
            get {
                return ResourceManager.GetString("SRemoveAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить фильтр.
        /// </summary>
        public static string SRemoveFilter {
            get {
                return ResourceManager.GetString("SRemoveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убрать группировку.
        /// </summary>
        public static string SRemoveGroupColumn {
            get {
                return ResourceManager.GetString("SRemoveGroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string SReport {
            get {
                return ResourceManager.GetString("SReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить поле &apos;{0}&apos;.
        /// </summary>
        public static string SRequiredFieldMessage {
            get {
                return ResourceManager.GetString("SRequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется указать обязательные фильтры. Для этого необходимо зайти в фильтры и заполнить те, у которых есть символ &quot;*&quot; в названии.
        /// </summary>
        public static string SRequiredFilters {
            get {
                return ResourceManager.GetString("SRequiredFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;{0}&apos; должно быть заполнено..
        /// </summary>
        public static string SRequiredReadOnlyFieldMessage {
            get {
                return ResourceManager.GetString("SRequiredReadOnlyFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к журналу.
        /// </summary>
        public static string SReturnToJournal {
            get {
                return ResourceManager.GetString("SReturnToJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезаписать настройки:.
        /// </summary>
        public static string SRewriteSettings {
            get {
                return ResourceManager.GetString("SRewriteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение не актуально (в архиве).
        /// </summary>
        public static string SRowArchive {
            get {
                return ResourceManager.GetString("SRowArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Залить строки цветом.
        /// </summary>
        public static string SRowColorFill {
            get {
                return ResourceManager.GetString("SRowColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указать цвет текста строки.
        /// </summary>
        public static string SRowFontColorFill {
            get {
                return ResourceManager.GetString("SRowFontColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбрана строка.
        /// </summary>
        public static string SRowIsNotSelected {
            get {
                return ResourceManager.GetString("SRowIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SSave {
            get {
                return ResourceManager.GetString("SSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить запись и открыть добавление новой записи.
        /// </summary>
        public static string SSaveAddToolTip {
            get {
                return ResourceManager.GetString("SSaveAddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить и добавить запись.
        /// </summary>
        public static string SSaveAndAddRecord {
            get {
                return ResourceManager.GetString("SSaveAndAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить фильтры.
        /// </summary>
        public static string SSaveFilters {
            get {
                return ResourceManager.GetString("SSaveFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить запись и перейти в журнал.
        /// </summary>
        public static string SSaveToolTip {
            get {
                return ResourceManager.GetString("SSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить заполненное.
        /// </summary>
        public static string SSaveValidated {
            get {
                return ResourceManager.GetString("SSaveValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить настройки представления.
        /// </summary>
        public static string SSaveViewSettings {
            get {
                return ResourceManager.GetString("SSaveViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение настроек представления.
        /// </summary>
        public static string SSaveViewSettingsHeader {
            get {
                return ResourceManager.GetString("SSaveViewSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить запись без истории.
        /// </summary>
        public static string SSaveWithoutHistory {
            get {
                return ResourceManager.GetString("SSaveWithoutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string SSavingJournal_Cancel {
            get {
                return ResourceManager.GetString("SSavingJournal_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить настройки.
        /// </summary>
        public static string SSavingJournal_Load {
            get {
                return ResourceManager.GetString("SSavingJournal_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SSavingJournal_Save {
            get {
                return ResourceManager.GetString("SSavingJournal_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string SSCApplyFixedHeader {
            get {
                return ResourceManager.GetString("SSCApplyFixedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string SSCApplyViewSettings {
            get {
                return ResourceManager.GetString("SSCApplyViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string SSCCancelViewSettings {
            get {
                return ResourceManager.GetString("SSCCancelViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество зафиксированных колонок.
        /// </summary>
        public static string SSCColsCountFixed {
            get {
                return ResourceManager.GetString("SSCColsCountFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зафиксировать заголовок.
        /// </summary>
        public static string SSCFixedHeader {
            get {
                return ResourceManager.GetString("SSCFixedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель заливки.
        /// </summary>
        public static string SSCParameters {
            get {
                return ResourceManager.GetString("SSCParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на if(confirm(&quot;В журнале {1} записей. Экспорт потребует некоторого времени. Возможно стоит пересмотреть фильтр что бы получить меньший список.&quot;)) return true; return false;.
        /// </summary>
        public static string SScriptExportAttentionCountRecords {
            get {
                return ResourceManager.GetString("SScriptExportAttentionCountRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на alert(&quot;Экспортировать больше {0} записей запрещено. Используйте фильтр что бы получить меньший список.&quot;); return false;.
        /// </summary>
        public static string SScriptExportMaxCountRecords {
            get {
                return ResourceManager.GetString("SScriptExportMaxCountRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество зафиксированных строк.
        /// </summary>
        public static string SSCRowsCountFixed {
            get {
                return ResourceManager.GetString("SSCRowsCountFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Искать.
        /// </summary>
        public static string SSearch {
            get {
                return ResourceManager.GetString("SSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск....
        /// </summary>
        public static string SSearchLoading {
            get {
                return ResourceManager.GetString("SSearchLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор записи.
        /// </summary>
        public static string SSelect {
            get {
                return ResourceManager.GetString("SSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать все записи со всех страниц.
        /// </summary>
        public static string SSelectAllFromAllPages {
            get {
                return ResourceManager.GetString("SSelectAllFromAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;lt;Выбрать условие&amp;gt;.
        /// </summary>
        public static string SSelectCondition {
            get {
                return ResourceManager.GetString("SSelectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранные.
        /// </summary>
        public static string SSelectedRowsDelete {
            get {
                return ResourceManager.GetString("SSelectedRowsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string SSelectText {
            get {
                return ResourceManager.GetString("SSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проводятся технические работы..
        /// </summary>
        public static string SServiceProcedure {
            get {
                return ResourceManager.GetString("SServiceProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С {0} планируется проводить {1}..
        /// </summary>
        public static string SServiceProcedure_BeforeEnabledMessage {
            get {
                return ResourceManager.GetString("SServiceProcedure_BeforeEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}, просим завершить текущие действия и выйти из системы. Обращение на новые страницы запрещено..
        /// </summary>
        public static string SServiceProcedure_CauseMessage {
            get {
                return ResourceManager.GetString("SServiceProcedure_CauseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические работы в текущий момент не проводятся..
        /// </summary>
        public static string SServiceProcedure_Disabled {
            get {
                return ResourceManager.GetString("SServiceProcedure_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические работы, просим завершить текущие действия и выйти из системы. Обращение на новые страницы запрещено..
        /// </summary>
        public static string SServiceProcedure_EnabledMessage {
            get {
                return ResourceManager.GetString("SServiceProcedure_EnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}..
        /// </summary>
        public static string SServiceProcedure_ServiceProcedureMessage {
            get {
                return ResourceManager.GetString("SServiceProcedure_ServiceProcedureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если в течении времени ({0}) нет обращений, то считается, что завершена работа на странице..
        /// </summary>
        public static string SServiceProcedure_TimeBetweenRequest {
            get {
                return ResourceManager.GetString("SServiceProcedure_TimeBetweenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предполагаемое время завершения {0}..
        /// </summary>
        public static string SServiceProcedure_TimeOfEndCause {
            get {
                return ResourceManager.GetString("SServiceProcedure_TimeOfEndCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предполагаемое время завершения технических работ {0}..
        /// </summary>
        public static string SServiceProcedure_TimeOfEndService {
            get {
                return ResourceManager.GetString("SServiceProcedure_TimeOfEndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С {0} планируется проводить технические работы..
        /// </summary>
        public static string SServiceProcedure_TimeToEnableMessage {
            get {
                return ResourceManager.GetString("SServiceProcedure_TimeToEnableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В {0} работа с системой будет не возможна..
        /// </summary>
        public static string SServiceProcedure_TimeToShutDown {
            get {
                return ResourceManager.GetString("SServiceProcedure_TimeToShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сессия устарела. Необходимо страницу открыть заново..
        /// </summary>
        public static string SSessionIsLost {
            get {
                return ResourceManager.GetString("SSessionIsLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать весь список фильтров.
        /// </summary>
        public static string SShowAllFilters {
            get {
                return ResourceManager.GetString("SShowAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести.
        /// </summary>
        public static string SShowDublicates {
            get {
                return ResourceManager.GetString("SShowDublicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать всем.
        /// </summary>
        public static string SShowForAll {
            get {
                return ResourceManager.GetString("SShowForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать историю.
        /// </summary>
        public static string SShowHistory {
            get {
                return ResourceManager.GetString("SShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать только основной список фильтров.
        /// </summary>
        public static string SShowMainGroupFilters {
            get {
                return ResourceManager.GetString("SShowMainGroupFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строить заголовок начиная с.
        /// </summary>
        public static string SStartHeaderFromLevel {
            get {
                return ResourceManager.GetString("SStartHeaderFromLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинается с.
        /// </summary>
        public static string SStartsWith {
            get {
                return ResourceManager.GetString("SStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписка.
        /// </summary>
        public static string SSubscription {
            get {
                return ResourceManager.GetString("SSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо изменить фильтр, т.к. за отведенное время не удалось выбрать необходимые данные..
        /// </summary>
        public static string STimeOut {
            get {
                return ResourceManager.GetString("STimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий день.
        /// </summary>
        public static string SToDay {
            get {
                return ResourceManager.GetString("SToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В журнал.
        /// </summary>
        public static string SToJournal {
            get {
                return ResourceManager.GetString("SToJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить влево.
        /// </summary>
        public static string SToLeft {
            get {
                return ResourceManager.GetString("SToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти в менеджер отчетов.
        /// </summary>
        public static string SToReportPlugin {
            get {
                return ResourceManager.GetString("SToReportPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить вправо.
        /// </summary>
        public static string SToRight {
            get {
                return ResourceManager.GetString("SToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string STotal {
            get {
                return ResourceManager.GetString("STotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого за {0}.
        /// </summary>
        public static string STotalFor {
            get {
                return ResourceManager.GetString("STotalFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снять выбор со всех страниц.
        /// </summary>
        public static string SUnselectAllFromAllPages {
            get {
                return ResourceManager.GetString("SUnselectAllFromAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SUpdateText {
            get {
                return ResourceManager.GetString("SUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поднять группу выше.
        /// </summary>
        public static string SUpGroup {
            get {
                return ResourceManager.GetString("SUpGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр.
        /// </summary>
        public static string SView {
            get {
                return ResourceManager.GetString("SView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к журналу.
        /// </summary>
        public static string SViewJournal {
            get {
                return ResourceManager.GetString("SViewJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр невозможен.
        /// </summary>
        public static string SViewNotAvailable {
            get {
                return ResourceManager.GetString("SViewNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка представления.
        /// </summary>
        public static string SViewSettings {
            get {
                return ResourceManager.GetString("SViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вертикальный заголовок.
        /// </summary>
        public static string SViewSettings_VerticalHeader {
            get {
                return ResourceManager.GetString("SViewSettings_VerticalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видимость колонки в журнале.
        /// </summary>
        public static string SViewSettings_Visible {
            get {
                return ResourceManager.GetString("SViewSettings_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки закрепления заголовка и колонок.
        /// </summary>
        public static string SViewSettingsFixedHeader {
            get {
                return ResourceManager.GetString("SViewSettingsFixedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина.
        /// </summary>
        public static string SWidth {
            get {
                return ResourceManager.GetString("SWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с уголком.
        /// </summary>
        public static string SWithCorner {
            get {
                return ResourceManager.GetString("SWithCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С уголком.
        /// </summary>
        public static string SWithCornerUpper {
            get {
                return ResourceManager.GetString("SWithCornerUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти далее.
        /// </summary>
        public static string SWizardNext {
            get {
                return ResourceManager.GetString("SWizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться назад.
        /// </summary>
        public static string SWizardPrevious {
            get {
                return ResourceManager.GetString("SWizardPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в MS Word.
        /// </summary>
        public static string SWordExport {
            get {
                return ResourceManager.GetString("SWordExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string SYes {
            get {
                return ResourceManager.GetString("SYes", resourceCulture);
            }
        }
    }
}
