#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Web.Tools.Security
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Default")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPersonInfoBySid")]
		public ISingleResult<GetPersonInfoBySidResult> GetPersonInfoBySid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string sid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sid);
			return ((ISingleResult<GetPersonInfoBySidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MSD_P_AddViewReports")]
		public int MSD_P_AddViewReports([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string sid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string loginName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> occurredDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(max)")] string docLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string siteUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string hostName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> siteID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> export, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(450)")] string reportPlugin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(450)")] string reportTitleRu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(450)")] string reportTitleKz)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sid, loginName, name, occurredDate, docLocation, siteUrl, hostName, siteID, export, reportPlugin, reportTitleRu, reportTitleKz);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ADM_P_SetUserActivityTime")]
		public int ADM_P_SetUserActivityTime([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string sid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ActivityDateTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sid, ActivityDateTime);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ADM_GetUsersInRole")]
		public ISingleResult<UsersInRoleResult> ADM_GetUsersInRole([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string permission)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), permission);
			return ((ISingleResult<UsersInRoleResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetPersonInfoBySidResult
	{
		
		private long _id;
		
		private System.Nullable<long> _refPosition;
		
		private System.Nullable<long> _refSubdivision;
		
		private System.Nullable<long> _refSubdivisionReal;
		
		private string _Fio_Ru;
		
		private string _Fio_Kz;
		
		private string _PositionNameRu;
		
		private string _PositionNameKz;
		
		private string _SubdivisionNameRu;
		
		private string _SubdivisionNameKz;
		
		private System.Nullable<long> _refRegion;
		
		private string _PositionCode;
		
		public GetPersonInfoBySidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refPosition", DbType="BigInt")]
		public System.Nullable<long> refPosition
		{
			get
			{
				return this._refPosition;
			}
			set
			{
				if ((this._refPosition != value))
				{
					this._refPosition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refSubdivision", DbType="BigInt")]
		public System.Nullable<long> refSubdivision
		{
			get
			{
				return this._refSubdivision;
			}
			set
			{
				if ((this._refSubdivision != value))
				{
					this._refSubdivision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refSubdivisionReal", DbType="BigInt")]
		public System.Nullable<long> refSubdivisionReal
		{
			get
			{
				return this._refSubdivisionReal;
			}
			set
			{
				if ((this._refSubdivisionReal != value))
				{
					this._refSubdivisionReal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fio_Ru", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Fio_Ru
		{
			get
			{
				return this._Fio_Ru;
			}
			set
			{
				if ((this._Fio_Ru != value))
				{
					this._Fio_Ru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fio_Kz", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Fio_Kz
		{
			get
			{
				return this._Fio_Kz;
			}
			set
			{
				if ((this._Fio_Kz != value))
				{
					this._Fio_Kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionNameRu", DbType="NVarChar(450)")]
		public string PositionNameRu
		{
			get
			{
				return this._PositionNameRu;
			}
			set
			{
				if ((this._PositionNameRu != value))
				{
					this._PositionNameRu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionNameKz", DbType="NVarChar(450)")]
		public string PositionNameKz
		{
			get
			{
				return this._PositionNameKz;
			}
			set
			{
				if ((this._PositionNameKz != value))
				{
					this._PositionNameKz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubdivisionNameRu", DbType="NVarChar(450)")]
		public string SubdivisionNameRu
		{
			get
			{
				return this._SubdivisionNameRu;
			}
			set
			{
				if ((this._SubdivisionNameRu != value))
				{
					this._SubdivisionNameRu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubdivisionNameKz", DbType="NVarChar(450)")]
		public string SubdivisionNameKz
		{
			get
			{
				return this._SubdivisionNameKz;
			}
			set
			{
				if ((this._SubdivisionNameKz != value))
				{
					this._SubdivisionNameKz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refRegion", DbType="BigInt")]
		public System.Nullable<long> refRegion
		{
			get
			{
				return this._refRegion;
			}
			set
			{
				if ((this._refRegion != value))
				{
					this._refRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionCode", DbType="NVarChar(255)")]
		public string PositionCode
		{
			get
			{
				return this._PositionCode;
			}
			set
			{
				if ((this._PositionCode != value))
				{
					this._PositionCode = value;
				}
			}
		}
	}
	
	public partial class UsersInRoleResult
	{
		
		private long _id;
		
		private string _Sid;
		
		private string _LoginName;
		
		private long _refUser;
		
		public UsersInRoleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sid", DbType="NVarChar(200) NOT NULL")]
		public string Sid
		{
			get
			{
				return this._Sid;
			}
			set
			{
				if ((this._Sid != value))
				{
					this._Sid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="NVarChar(200) NULL")]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this._LoginName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refUser", DbType="BigInt NOT NULL")]
		public long refUser
		{
			get
			{
				return this._refUser;
			}
			set
			{
				if ((this._refUser != value))
				{
					this._refUser = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
