#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Web.Controls.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Default")]
	internal partial class DB_RvsSettingsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRVS_Export(RVS_Export instance);
    partial void UpdateRVS_Export(RVS_Export instance);
    partial void DeleteRVS_Export(RVS_Export instance);
    partial void InsertRVS_SavedProperty(RVS_SavedProperty instance);
    partial void UpdateRVS_SavedProperty(RVS_SavedProperty instance);
    partial void DeleteRVS_SavedProperty(RVS_SavedProperty instance);
    partial void InsertRVS_Property(RVS_Property instance);
    partial void UpdateRVS_Property(RVS_Property instance);
    partial void DeleteRVS_Property(RVS_Property instance);
    partial void InsertLOG_SidIdentification(LOG_SidIdentification instance);
    partial void UpdateLOG_SidIdentification(LOG_SidIdentification instance);
    partial void DeleteLOG_SidIdentification(LOG_SidIdentification instance);
    #endregion
		
		public DB_RvsSettingsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_RvsSettingsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_RvsSettingsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_RvsSettingsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_RvsSettingsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RVS_Export> RVS_Exports
		{
			get
			{
				return this.GetTable<RVS_Export>();
			}
		}
		
		public System.Data.Linq.Table<RVS_SavedProperty> RVS_SavedProperties
		{
			get
			{
				return this.GetTable<RVS_SavedProperty>();
			}
		}
		
		public System.Data.Linq.Table<RVS_Property> RVS_Properties
		{
			get
			{
				return this.GetTable<RVS_Property>();
			}
		}
		
		public System.Data.Linq.Table<LOG_SidIdentification> LOG_SidIdentifications
		{
			get
			{
				return this.GetTable<LOG_SidIdentification>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RVS_Exports")]
	public partial class RVS_Export : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.DateTime _dateTime;
		
		private long _refProperties;
		
		private long _refSid;
		
		private EntityRef<RVS_Property> _RVS_Property;
		
		private EntityRef<LOG_SidIdentification> _LOG_SidIdentification;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndateTimeChanging(System.DateTime value);
    partial void OndateTimeChanged();
    partial void OnrefPropertiesChanging(long value);
    partial void OnrefPropertiesChanged();
    partial void OnrefSidChanging(long value);
    partial void OnrefSidChanged();
    #endregion
		
		public RVS_Export()
		{
			this._RVS_Property = default(EntityRef<RVS_Property>);
			this._LOG_SidIdentification = default(EntityRef<LOG_SidIdentification>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateTime", DbType="DateTime NOT NULL")]
		public System.DateTime dateTime
		{
			get
			{
				return this._dateTime;
			}
			set
			{
				if ((this._dateTime != value))
				{
					this.OndateTimeChanging(value);
					this.SendPropertyChanging();
					this._dateTime = value;
					this.SendPropertyChanged("dateTime");
					this.OndateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refProperties", DbType="BigInt NOT NULL")]
		public long refProperties
		{
			get
			{
				return this._refProperties;
			}
			set
			{
				if ((this._refProperties != value))
				{
					if (this._RVS_Property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrefPropertiesChanging(value);
					this.SendPropertyChanging();
					this._refProperties = value;
					this.SendPropertyChanged("refProperties");
					this.OnrefPropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refSid", DbType="BigInt NOT NULL")]
		public long refSid
		{
			get
			{
				return this._refSid;
			}
			set
			{
				if ((this._refSid != value))
				{
					if (this._LOG_SidIdentification.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrefSidChanging(value);
					this.SendPropertyChanging();
					this._refSid = value;
					this.SendPropertyChanged("refSid");
					this.OnrefSidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RVS_Property_RVS_Export", Storage="_RVS_Property", ThisKey="refProperties", OtherKey="id", IsForeignKey=true)]
		public RVS_Property RVS_Property
		{
			get
			{
				return this._RVS_Property.Entity;
			}
			set
			{
				RVS_Property previousValue = this._RVS_Property.Entity;
				if (((previousValue != value) 
							|| (this._RVS_Property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RVS_Property.Entity = null;
						previousValue.RVS_Exports.Remove(this);
					}
					this._RVS_Property.Entity = value;
					if ((value != null))
					{
						value.RVS_Exports.Add(this);
						this._refProperties = value.id;
					}
					else
					{
						this._refProperties = default(long);
					}
					this.SendPropertyChanged("RVS_Property");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOG_SidIdentification_RVS_Export", Storage="_LOG_SidIdentification", ThisKey="refSid", OtherKey="ID", IsForeignKey=true)]
		public LOG_SidIdentification LOG_SidIdentification
		{
			get
			{
				return this._LOG_SidIdentification.Entity;
			}
			set
			{
				LOG_SidIdentification previousValue = this._LOG_SidIdentification.Entity;
				if (((previousValue != value) 
							|| (this._LOG_SidIdentification.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOG_SidIdentification.Entity = null;
						previousValue.RVS_Exports.Remove(this);
					}
					this._LOG_SidIdentification.Entity = value;
					if ((value != null))
					{
						value.RVS_Exports.Add(this);
						this._refSid = value.ID;
					}
					else
					{
						this._refSid = default(long);
					}
					this.SendPropertyChanged("LOG_SidIdentification");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RVS_SavedProperties")]
	public partial class RVS_SavedProperty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _nameKz;
		
		private string _nameRu;
		
		private long _refProperties;
		
		private System.DateTime _dateTime;
		
		private long _refSid;
		
		private string _JournalTypeName;
		
		private bool _isDefaultView;
		
		private bool _isSharedView;
		
		private string _context;
		
		private EntityRef<RVS_Property> _RVS_Property;
		
		private EntityRef<LOG_SidIdentification> _LOG_SidIdentification;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameKzChanging(string value);
    partial void OnnameKzChanged();
    partial void OnnameRuChanging(string value);
    partial void OnnameRuChanged();
    partial void OnrefPropertiesChanging(long value);
    partial void OnrefPropertiesChanged();
    partial void OndateTimeChanging(System.DateTime value);
    partial void OndateTimeChanged();
    partial void OnrefSidChanging(long value);
    partial void OnrefSidChanged();
    partial void OnJournalTypeNameChanging(string value);
    partial void OnJournalTypeNameChanged();
    partial void OnisDefaultViewChanging(bool value);
    partial void OnisDefaultViewChanged();
    partial void OnisSharedViewChanging(bool value);
    partial void OnisSharedViewChanged();
    partial void OncontextChanging(string value);
    partial void OncontextChanged();
    #endregion
		
		public RVS_SavedProperty()
		{
			this._RVS_Property = default(EntityRef<RVS_Property>);
			this._LOG_SidIdentification = default(EntityRef<LOG_SidIdentification>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameKz", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nameKz
		{
			get
			{
				return this._nameKz;
			}
			set
			{
				if ((this._nameKz != value))
				{
					this.OnnameKzChanging(value);
					this.SendPropertyChanging();
					this._nameKz = value;
					this.SendPropertyChanged("nameKz");
					this.OnnameKzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameRu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nameRu
		{
			get
			{
				return this._nameRu;
			}
			set
			{
				if ((this._nameRu != value))
				{
					this.OnnameRuChanging(value);
					this.SendPropertyChanging();
					this._nameRu = value;
					this.SendPropertyChanged("nameRu");
					this.OnnameRuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refProperties", DbType="BigInt NOT NULL")]
		public long refProperties
		{
			get
			{
				return this._refProperties;
			}
			set
			{
				if ((this._refProperties != value))
				{
					if (this._RVS_Property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrefPropertiesChanging(value);
					this.SendPropertyChanging();
					this._refProperties = value;
					this.SendPropertyChanged("refProperties");
					this.OnrefPropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateTime", DbType="DateTime NOT NULL")]
		public System.DateTime dateTime
		{
			get
			{
				return this._dateTime;
			}
			set
			{
				if ((this._dateTime != value))
				{
					this.OndateTimeChanging(value);
					this.SendPropertyChanging();
					this._dateTime = value;
					this.SendPropertyChanged("dateTime");
					this.OndateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refSid", DbType="BigInt NOT NULL")]
		public long refSid
		{
			get
			{
				return this._refSid;
			}
			set
			{
				if ((this._refSid != value))
				{
					if (this._LOG_SidIdentification.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrefSidChanging(value);
					this.SendPropertyChanging();
					this._refSid = value;
					this.SendPropertyChanged("refSid");
					this.OnrefSidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JournalTypeName", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string JournalTypeName
		{
			get
			{
				return this._JournalTypeName;
			}
			set
			{
				if ((this._JournalTypeName != value))
				{
					this.OnJournalTypeNameChanging(value);
					this.SendPropertyChanging();
					this._JournalTypeName = value;
					this.SendPropertyChanged("JournalTypeName");
					this.OnJournalTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDefaultView", DbType="Bit NOT NULL")]
		public bool isDefaultView
		{
			get
			{
				return this._isDefaultView;
			}
			set
			{
				if ((this._isDefaultView != value))
				{
					this.OnisDefaultViewChanging(value);
					this.SendPropertyChanging();
					this._isDefaultView = value;
					this.SendPropertyChanged("isDefaultView");
					this.OnisDefaultViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSharedView", DbType="Bit NOT NULL")]
		public bool isSharedView
		{
			get
			{
				return this._isSharedView;
			}
			set
			{
				if ((this._isSharedView != value))
				{
					this.OnisSharedViewChanging(value);
					this.SendPropertyChanging();
					this._isSharedView = value;
					this.SendPropertyChanged("isSharedView");
					this.OnisSharedViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_context", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string context
		{
			get
			{
				return this._context;
			}
			set
			{
				if ((this._context != value))
				{
					this.OncontextChanging(value);
					this.SendPropertyChanging();
					this._context = value;
					this.SendPropertyChanged("context");
					this.OncontextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RVS_Property_RVS_SavedProperty", Storage="_RVS_Property", ThisKey="refProperties", OtherKey="id", IsForeignKey=true)]
		public RVS_Property RVS_Property
		{
			get
			{
				return this._RVS_Property.Entity;
			}
			set
			{
				RVS_Property previousValue = this._RVS_Property.Entity;
				if (((previousValue != value) 
							|| (this._RVS_Property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RVS_Property.Entity = null;
						previousValue.RVS_SavedProperties.Remove(this);
					}
					this._RVS_Property.Entity = value;
					if ((value != null))
					{
						value.RVS_SavedProperties.Add(this);
						this._refProperties = value.id;
					}
					else
					{
						this._refProperties = default(long);
					}
					this.SendPropertyChanged("RVS_Property");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOG_SidIdentification_RVS_SavedProperty", Storage="_LOG_SidIdentification", ThisKey="refSid", OtherKey="ID", IsForeignKey=true)]
		public LOG_SidIdentification LOG_SidIdentification
		{
			get
			{
				return this._LOG_SidIdentification.Entity;
			}
			set
			{
				LOG_SidIdentification previousValue = this._LOG_SidIdentification.Entity;
				if (((previousValue != value) 
							|| (this._LOG_SidIdentification.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOG_SidIdentification.Entity = null;
						previousValue.RVS_SavedProperties.Remove(this);
					}
					this._LOG_SidIdentification.Entity = value;
					if ((value != null))
					{
						value.RVS_SavedProperties.Add(this);
						this._refSid = value.ID;
					}
					else
					{
						this._refSid = default(long);
					}
					this.SendPropertyChanged("LOG_SidIdentification");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RVS_Properties")]
	public partial class RVS_Property : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _nameKz;
		
		private string _nameRu;
		
		private string _JournalTypeName;
		
		private System.Xml.Linq.XElement _Gouping;
		
		private System.Xml.Linq.XElement _Filter;
		
		private System.Xml.Linq.XElement _ColumnsVisible;
		
		private System.Xml.Linq.XElement _ColumnsStyle;
		
		private System.Xml.Linq.XElement _RowsStyle;
		
		private System.Xml.Linq.XElement _CellsStyle;
		
		private System.Xml.Linq.XElement _FixedHeader;
		
		private System.Data.Linq.Binary _StorageValues;
		
		private string _ReportPluginName;
		
		private System.Xml.Linq.XElement _OrderByColumns;
		
		private System.Xml.Linq.XElement _OtherParameters;
		
		private EntitySet<RVS_Export> _RVS_Exports;
		
		private EntitySet<RVS_SavedProperty> _RVS_SavedProperties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameKzChanging(string value);
    partial void OnnameKzChanged();
    partial void OnnameRuChanging(string value);
    partial void OnnameRuChanged();
    partial void OnJournalTypeNameChanging(string value);
    partial void OnJournalTypeNameChanged();
    partial void OnGroupingChanging(System.Xml.Linq.XElement value);
    partial void OnGroupingChanged();
    partial void OnFilterChanging(System.Xml.Linq.XElement value);
    partial void OnFilterChanged();
    partial void OnColumnsVisibleChanging(System.Xml.Linq.XElement value);
    partial void OnColumnsVisibleChanged();
    partial void OnColumnsStyleChanging(System.Xml.Linq.XElement value);
    partial void OnColumnsStyleChanged();
    partial void OnRowsStyleChanging(System.Xml.Linq.XElement value);
    partial void OnRowsStyleChanged();
    partial void OnCellsStyleChanging(System.Xml.Linq.XElement value);
    partial void OnCellsStyleChanged();
    partial void OnFixedHeaderChanging(System.Xml.Linq.XElement value);
    partial void OnFixedHeaderChanged();
    partial void OnStorageValuesChanging(System.Data.Linq.Binary value);
    partial void OnStorageValuesChanged();
    partial void OnReportPluginNameChanging(string value);
    partial void OnReportPluginNameChanged();
    partial void OnOrderByColumnsChanging(System.Xml.Linq.XElement value);
    partial void OnOrderByColumnsChanged();
    partial void OnOtherParametersChanging(System.Xml.Linq.XElement value);
    partial void OnOtherParametersChanged();
    #endregion
		
		public RVS_Property()
		{
			this._RVS_Exports = new EntitySet<RVS_Export>(new Action<RVS_Export>(this.attach_RVS_Exports), new Action<RVS_Export>(this.detach_RVS_Exports));
			this._RVS_SavedProperties = new EntitySet<RVS_SavedProperty>(new Action<RVS_SavedProperty>(this.attach_RVS_SavedProperties), new Action<RVS_SavedProperty>(this.detach_RVS_SavedProperties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameKz", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string nameKz
		{
			get
			{
				return this._nameKz;
			}
			set
			{
				if ((this._nameKz != value))
				{
					this.OnnameKzChanging(value);
					this.SendPropertyChanging();
					this._nameKz = value;
					this.SendPropertyChanged("nameKz");
					this.OnnameKzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameRu", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string nameRu
		{
			get
			{
				return this._nameRu;
			}
			set
			{
				if ((this._nameRu != value))
				{
					this.OnnameRuChanging(value);
					this.SendPropertyChanging();
					this._nameRu = value;
					this.SendPropertyChanged("nameRu");
					this.OnnameRuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JournalTypeName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string JournalTypeName
		{
			get
			{
				return this._JournalTypeName;
			}
			set
			{
				if ((this._JournalTypeName != value))
				{
					this.OnJournalTypeNameChanging(value);
					this.SendPropertyChanging();
					this._JournalTypeName = value;
					this.SendPropertyChanged("JournalTypeName");
					this.OnJournalTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gouping", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement Grouping
		{
			get
			{
				return this._Gouping;
			}
			set
			{
				if ((this._Gouping != value))
				{
					this.OnGroupingChanging(value);
					this.SendPropertyChanging();
					this._Gouping = value;
					this.SendPropertyChanged("Grouping");
					this.OnGroupingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filter", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement Filter
		{
			get
			{
				return this._Filter;
			}
			set
			{
				if ((this._Filter != value))
				{
					this.OnFilterChanging(value);
					this.SendPropertyChanging();
					this._Filter = value;
					this.SendPropertyChanged("Filter");
					this.OnFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnsVisible", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement ColumnsVisible
		{
			get
			{
				return this._ColumnsVisible;
			}
			set
			{
				if ((this._ColumnsVisible != value))
				{
					this.OnColumnsVisibleChanging(value);
					this.SendPropertyChanging();
					this._ColumnsVisible = value;
					this.SendPropertyChanged("ColumnsVisible");
					this.OnColumnsVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnsStyle", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement ColumnsStyle
		{
			get
			{
				return this._ColumnsStyle;
			}
			set
			{
				if ((this._ColumnsStyle != value))
				{
					this.OnColumnsStyleChanging(value);
					this.SendPropertyChanging();
					this._ColumnsStyle = value;
					this.SendPropertyChanged("ColumnsStyle");
					this.OnColumnsStyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowsStyle", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement RowsStyle
		{
			get
			{
				return this._RowsStyle;
			}
			set
			{
				if ((this._RowsStyle != value))
				{
					this.OnRowsStyleChanging(value);
					this.SendPropertyChanging();
					this._RowsStyle = value;
					this.SendPropertyChanged("RowsStyle");
					this.OnRowsStyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellsStyle", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement CellsStyle
		{
			get
			{
				return this._CellsStyle;
			}
			set
			{
				if ((this._CellsStyle != value))
				{
					this.OnCellsStyleChanging(value);
					this.SendPropertyChanging();
					this._CellsStyle = value;
					this.SendPropertyChanged("CellsStyle");
					this.OnCellsStyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FixedHeader", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement FixedHeader
		{
			get
			{
				return this._FixedHeader;
			}
			set
			{
				if ((this._FixedHeader != value))
				{
					this.OnFixedHeaderChanging(value);
					this.SendPropertyChanging();
					this._FixedHeader = value;
					this.SendPropertyChanged("FixedHeader");
					this.OnFixedHeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorageValues", DbType="varbinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StorageValues
		{
			get
			{
				return this._StorageValues;
			}
			set
			{
				if ((this._StorageValues != value))
				{
					this.OnStorageValuesChanging(value);
					this.SendPropertyChanging();
					this._StorageValues = value;
					this.SendPropertyChanged("StorageValues");
					this.OnStorageValuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportPluginName", DbType="nvarchar(500)", UpdateCheck=UpdateCheck.Never)]
		public string ReportPluginName
		{
			get
			{
				return this._ReportPluginName;
			}
			set
			{
				if ((this._ReportPluginName != value))
				{
					this.OnReportPluginNameChanging(value);
					this.SendPropertyChanging();
					this._ReportPluginName = value;
					this.SendPropertyChanged("ReportPluginName");
					this.OnReportPluginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderByColumns", DbType="Xml", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement OrderByColumns
		{
			get
			{
				return this._OrderByColumns;
			}
			set
			{
				if ((this._OrderByColumns != value))
				{
					this.OnOrderByColumnsChanging(value);
					this.SendPropertyChanging();
					this._OrderByColumns = value;
					this.SendPropertyChanged("OrderByColumns");
					this.OnOrderByColumnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherParameters", DbType="Xml", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement OtherParameters
		{
			get
			{
				return this._OtherParameters;
			}
			set
			{
				if ((this._OtherParameters != value))
				{
					this.OnOtherParametersChanging(value);
					this.SendPropertyChanging();
					this._OtherParameters = value;
					this.SendPropertyChanged("OtherParameters");
					this.OnOtherParametersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RVS_Property_RVS_Export", Storage="_RVS_Exports", ThisKey="id", OtherKey="refProperties")]
		public EntitySet<RVS_Export> RVS_Exports
		{
			get
			{
				return this._RVS_Exports;
			}
			set
			{
				this._RVS_Exports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RVS_Property_RVS_SavedProperty", Storage="_RVS_SavedProperties", ThisKey="id", OtherKey="refProperties")]
		public EntitySet<RVS_SavedProperty> RVS_SavedProperties
		{
			get
			{
				return this._RVS_SavedProperties;
			}
			set
			{
				this._RVS_SavedProperties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RVS_Exports(RVS_Export entity)
		{
			this.SendPropertyChanging();
			entity.RVS_Property = this;
		}
		
		private void detach_RVS_Exports(RVS_Export entity)
		{
			this.SendPropertyChanging();
			entity.RVS_Property = null;
		}
		
		private void attach_RVS_SavedProperties(RVS_SavedProperty entity)
		{
			this.SendPropertyChanging();
			entity.RVS_Property = this;
		}
		
		private void detach_RVS_SavedProperties(RVS_SavedProperty entity)
		{
			this.SendPropertyChanging();
			entity.RVS_Property = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOG_SidIdentification")]
	public partial class LOG_SidIdentification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Sid;
		
		private string _Name;
		
		private string _email;
		
		private bool _isDisabled;
		
		private EntitySet<RVS_Export> _RVS_Exports;
		
		private EntitySet<RVS_SavedProperty> _RVS_SavedProperties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnSidChanging(string value);
    partial void OnSidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnisDisabledChanging(bool value);
    partial void OnisDisabledChanged();
    #endregion
		
		public LOG_SidIdentification()
		{
			this._RVS_Exports = new EntitySet<RVS_Export>(new Action<RVS_Export>(this.attach_RVS_Exports), new Action<RVS_Export>(this.detach_RVS_Exports));
			this._RVS_SavedProperties = new EntitySet<RVS_SavedProperty>(new Action<RVS_SavedProperty>(this.attach_RVS_SavedProperties), new Action<RVS_SavedProperty>(this.detach_RVS_SavedProperties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sid", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Sid
		{
			get
			{
				return this._Sid;
			}
			set
			{
				if ((this._Sid != value))
				{
					this.OnSidChanging(value);
					this.SendPropertyChanging();
					this._Sid = value;
					this.SendPropertyChanged("Sid");
					this.OnSidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDisabled", DbType="Bit NOT NULL")]
		public bool isDisabled
		{
			get
			{
				return this._isDisabled;
			}
			set
			{
				if ((this._isDisabled != value))
				{
					this.OnisDisabledChanging(value);
					this.SendPropertyChanging();
					this._isDisabled = value;
					this.SendPropertyChanged("isDisabled");
					this.OnisDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOG_SidIdentification_RVS_Export", Storage="_RVS_Exports", ThisKey="ID", OtherKey="refSid")]
		public EntitySet<RVS_Export> RVS_Exports
		{
			get
			{
				return this._RVS_Exports;
			}
			set
			{
				this._RVS_Exports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOG_SidIdentification_RVS_SavedProperty", Storage="_RVS_SavedProperties", ThisKey="ID", OtherKey="refSid")]
		public EntitySet<RVS_SavedProperty> RVS_SavedProperties
		{
			get
			{
				return this._RVS_SavedProperties;
			}
			set
			{
				this._RVS_SavedProperties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RVS_Exports(RVS_Export entity)
		{
			this.SendPropertyChanging();
			entity.LOG_SidIdentification = this;
		}
		
		private void detach_RVS_Exports(RVS_Export entity)
		{
			this.SendPropertyChanging();
			entity.LOG_SidIdentification = null;
		}
		
		private void attach_RVS_SavedProperties(RVS_SavedProperty entity)
		{
			this.SendPropertyChanging();
			entity.LOG_SidIdentification = this;
		}
		
		private void detach_RVS_SavedProperties(RVS_SavedProperty entity)
		{
			this.SendPropertyChanging();
			entity.LOG_SidIdentification = null;
		}
	}
}
#pragma warning restore 1591
