#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Web.Controls.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Default")]
	internal partial class DBTraceTimingRequestsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBTraceTimingRequestsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTraceTimingRequestsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTraceTimingRequestsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTraceTimingRequestsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTraceTimingRequestsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.P_LOG_UpdateTraceTimingRequest")]
		public int P_LOG_UpdateTraceTimingRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TraceKey", DbType="uniqueidentifier")] System.Nullable<System.Guid> traceKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeOfDestinationUser", DbType="BigInt")] System.Nullable<long> timeOfDestinationUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), traceKey, timeOfDestinationUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.P_LOG_InsertTraceTimingRequest")]
		public int P_LOG_InsertTraceTimingRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="NVarChar(255)")] string page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(MAX)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateTimeStart", DbType="DateTime")] System.Nullable<System.DateTime> dateTimeStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeOfCreatingPage", DbType="BigInt")] System.Nullable<long> timeOfCreatingPage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> refUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> refRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TableName", DbType="NVarChar(255)")] string tableName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SelectMode", DbType="NVarChar(255)")] string selectMode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageType", DbType="NVarChar(255)")] string pageType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Parameters", DbType="Xml")] System.Xml.Linq.XElement parameters, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Trace", DbType="Xml")] System.Xml.Linq.XElement trace, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TraceKey", DbType="uniqueidentifier")] System.Nullable<System.Guid> traceKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), page, url, dateTimeStart, timeOfCreatingPage, refUser, refRegion, tableName, selectMode, pageType, parameters, trace, traceKey, id);
			id = ((System.Nullable<long>)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
