#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Web.Controls.GenerationClasses.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Default")]
	public partial class CrossJournalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSYS_CrossJournalEdit(SYS_CrossJournalEdit instance);
    partial void UpdateSYS_CrossJournalEdit(SYS_CrossJournalEdit instance);
    partial void DeleteSYS_CrossJournalEdit(SYS_CrossJournalEdit instance);
    #endregion
		
		public CrossJournalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CrossJournalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrossJournalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrossJournalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrossJournalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYS_CrossJournalEdit> SYS_CrossJournalEdits
		{
			get
			{
				return this.GetTable<SYS_CrossJournalEdit>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SYS_GetCrossJournalEdits")]
		public ISingleResult<SYS_GetCrossJournalEditsResult> SYS_GetCrossJournalEdits([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SID", DbType="NVarChar(255)")] string sID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JorunalName", DbType="NVarChar(MAX)")] string jorunalName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RowID", DbType="NVarChar(MAX)")] string rowID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string crossHeaderName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CrossRowID", DbType="NVarChar(MAX)")] string crossRowID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> startEdit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> endEdit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sID, jorunalName, rowID, crossHeaderName, crossRowID, startEdit, endEdit);
			return ((ISingleResult<SYS_GetCrossJournalEditsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SYS_UpdateCrossJournalEdits")]
		public ISingleResult<SYS_UpdateCrossJournalEditsResult> SYS_UpdateCrossJournalEdits([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SID", DbType="NVarChar(255)")] string sID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JorunalName", DbType="NVarChar(MAX)")] string jorunalName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RowID", DbType="NVarChar(MAX)")] string rowID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sID, jorunalName, rowID);
			return ((ISingleResult<SYS_UpdateCrossJournalEditsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_CrossJournalEdits")]
	public partial class SYS_CrossJournalEdit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _SID;
		
		private System.DateTime _dtStart;
		
		private System.DateTime _dtLast;
		
		private bool _endEdit;
		
		private string _journalName;
		
		private string _rowID;
		
		private string _crossRowID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnSIDChanging(string value);
    partial void OnSIDChanged();
    partial void OndtStartChanging(System.DateTime value);
    partial void OndtStartChanged();
    partial void OndtLastChanging(System.DateTime value);
    partial void OndtLastChanged();
    partial void OnendEditChanging(bool value);
    partial void OnendEditChanged();
    partial void OnjournalNameChanging(string value);
    partial void OnjournalNameChanged();
    partial void OnrowIDChanging(string value);
    partial void OnrowIDChanged();
    partial void OncrossRowIDChanging(string value);
    partial void OncrossRowIDChanged();
    #endregion
		
		public SYS_CrossJournalEdit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtStart", DbType="DateTime NOT NULL")]
		public System.DateTime dtStart
		{
			get
			{
				return this._dtStart;
			}
			set
			{
				if ((this._dtStart != value))
				{
					this.OndtStartChanging(value);
					this.SendPropertyChanging();
					this._dtStart = value;
					this.SendPropertyChanged("dtStart");
					this.OndtStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLast", DbType="DateTime NOT NULL")]
		public System.DateTime dtLast
		{
			get
			{
				return this._dtLast;
			}
			set
			{
				if ((this._dtLast != value))
				{
					this.OndtLastChanging(value);
					this.SendPropertyChanging();
					this._dtLast = value;
					this.SendPropertyChanged("dtLast");
					this.OndtLastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endEdit", DbType="Bit NOT NULL")]
		public bool endEdit
		{
			get
			{
				return this._endEdit;
			}
			set
			{
				if ((this._endEdit != value))
				{
					this.OnendEditChanging(value);
					this.SendPropertyChanging();
					this._endEdit = value;
					this.SendPropertyChanged("endEdit");
					this.OnendEditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_journalName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string journalName
		{
			get
			{
				return this._journalName;
			}
			set
			{
				if ((this._journalName != value))
				{
					this.OnjournalNameChanging(value);
					this.SendPropertyChanging();
					this._journalName = value;
					this.SendPropertyChanged("journalName");
					this.OnjournalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowID", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string rowID
		{
			get
			{
				return this._rowID;
			}
			set
			{
				if ((this._rowID != value))
				{
					this.OnrowIDChanging(value);
					this.SendPropertyChanging();
					this._rowID = value;
					this.SendPropertyChanged("rowID");
					this.OnrowIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crossRowID", DbType="NVarChar(MAX)")]
		public string crossRowID
		{
			get
			{
				return this._crossRowID;
			}
			set
			{
				if ((this._crossRowID != value))
				{
					this.OncrossRowIDChanging(value);
					this.SendPropertyChanging();
					this._crossRowID = value;
					this.SendPropertyChanged("crossRowID");
					this.OncrossRowIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SYS_GetCrossJournalEditsResult
	{
		
		private System.Nullable<long> _id;
		
		private string _SID;
		
		private System.Nullable<System.DateTime> _dtLast;
		
		public SYS_GetCrossJournalEditsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt")]
		public System.Nullable<long> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(255)")]
		public string SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLast", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtLast
		{
			get
			{
				return this._dtLast;
			}
			set
			{
				if ((this._dtLast != value))
				{
					this._dtLast = value;
				}
			}
		}
	}
	
	public partial class SYS_UpdateCrossJournalEditsResult
	{
		
		private System.Nullable<bool> _Result;
		
		public SYS_UpdateCrossJournalEditsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Bit")]
		public System.Nullable<bool> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
